SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;

--
-- CREATE TABLE `Superheroes`
--

CREATE TABLE IF NOT EXISTS `Superheroes` (
  `hero_id` tinyint(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `fullName` varchar(50) NOT NULL,
  `gender` varchar(5) NOT NULL,
  `universe` varchar(1000) NOT NULL,
  `race` varchar(1000) NOT NULL,
  `powers` varchar(1000) NOT NULL,
  `img` varchar(1000) NOT NULL,
  `bio` varchar(5000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- 
-- INSERT SUPERHERO DATA
-- 


INSERT INTO `Superheroes` (`hero_id`, `name`, `fullName`, `gender`, `universe`, `race`, `powers`, `img`, `bio`) VALUES
(1, 'Spider-Man', 'Peter Parker', 'M', 'Marvel Universe', 'Mutant', 'Spider senses, web shooting, super strength, stick to solid surfaces, superhuman agility, intellect', 'https://cdn.vox-cdn.com/thumbor/yvewlXndhBYW1xl690fF9HclFHg=/0x0:1800x2651/1200x800/filters:focal(738x1398:1026x1686)/cdn.vox-cdn.com/uploads/chorus_image/image/60074609/SGEDDON2018000cov.0.jpg', 'Bitten by a radioactive spider, Peter Parker’s arachnid abilities give him amazing powers he uses to help others, while his personal life continues to offer plenty of obstacles.'),
(2, 'Superman', 'Clark Kent', 'M', 'DC Universe', 'Alien', 'Communication with Spiders, Super strength, Super healing, Night vision, Shooting web, Super agility and speed, Wall crawling, Spidey-sense, and Web slinging.', 'https://upload.wikimedia.org/wikipedia/en/e/eb/SupermanRoss.png', 'Peter Parker was an orphaned teenage boy who lived in Queens, New York with his Aunt May and Uncle Ben. He was a shy boy, but highly intelligent and excelled in science. He was often teased by other more popular kids like longtime nemesis Flash Thompson, but his life was soon to change on a visit to the science museum.At the science museum, Peter was bitten by a radioactive spider. The spider bite gave Peter spider-like powers with super strength and reflexes. He also had a spider-sense alerting him to danger. Armed with these new powers, Peter first sought fame and money before fighting crime. He worked with a wrestling circuit and got some fame and appeared on a television show. During a robbery of the television show, Peter has the chance to stop the thief but chose not to.Peter later finds out that the same robber that he could have stopped at the television studio attempted to rob his aunt and uncle\'s residence, and his Uncle Ben was killed in the struggle. The words of his late uncle, with great power there must also come great responsibility, drive Peter to fight crime instead of chasing fame. Spider-Man was truly born.'),
(3, 'Batman', 'Bruce Wayne', 'M', 'DC Universe', 'Human', 'Adaptive, Agility, Energy Based Constructs, Escape Artist, Gadgets, Insanely Rich, Intellect, Leadership, Marksmanship, Power Suit, Stamina, Stealth, Swordsmanship, Tracking, Unarmed Combat, and Weapon Master\n', 'https://upload.wikimedia.org/wikipedia/en/8/87/Batman_DC_Comics.png', 'Bruce Wayne, who witnessed the murder of his billionaire parents as a child, swore to avenge their deaths. He trained extensively to achieve mental and physical perfection, mastering martial arts, detective skills, and criminal psychology. Costumed as a bat to prey on the fears of criminals, and utilizing a high-tech arsenal, he became the legendary Batman.'),
(4, 'Wonder Woman', 'Diana Prince', 'F', 'DC Universe', 'Other', 'Agility, Animal Control, Berserker Strength, Divine Powers, Flight, Healing, Immortal, Insanely Rich, Intellect, Invulnerability, Leadership, Longevity, Magic, Power Item, Stamina, Super Hearing, Super Speed, Super Strength, Swordsmanship, Unarmed Combat, and Weapon Master', 'https://upload.wikimedia.org/wikipedia/en/9/93/Wonder_Woman.jpg', 'The princess of the Amazons, armed with powers of a god, Wonder Woman is one of Earth\'s most powerful defenders of peace and equality and a member of the Justice League. She is often considered an archetype for the comic book superheroine. She stands for Love, peace, and above all else, truth! Her original origin depicted her as a clay figure brought to life by the gods, but in recent years she has been depicted as the daughter of Zeus and the Amazon queen Hippolyta.'),
(5, 'Black Canary', 'Dinah Lance', 'F', 'DC Universe', 'Human', 'Agility, Escape Artist, Flight, Gadgets, Intellect, Leadership, Marksmanship, Power Suit, Sonic Scream, Stamina, Stealth, Swordsmanship, Tracking, Unarmed Combat, Voice-induced Manipulation, and Weapon Master.', 'https://upload.wikimedia.org/wikipedia/en/6/61/Black_Canary_BOP.jpg', 'Dinah Lance was born into a family of crime fighters; her mother was a vigilante and her father is a cop. She grew up with the company of heroes, and after years of training, followed in her parent\'s footsteps by assuming the costume, identity, and legacy of her mother Dinah Drake, the Black Canary.'),
(6, 'Flash', 'Barry Allen', 'M', 'DC Universe', 'Human', 'Agility, Blast Power, Electricity Control, Energy Absorption, Energy-Enhanced Strike, Force Field, Healing, Heat Generation, Inertia Absorption, Intellect, Invisibility, Leadership, Light Projection, Magnetism, Phasing/Ghost, Stamina, Super Sight, Super Speed, Time Manipulation, Time Travel, Unarmed Combat, and Wind Bursts.', 'https://static.comicvine.com/uploads/scale_small/12/120019/3362537-100_11201.jpg', 'Having discovered his mother murdered and his father blamed for the act, forensic scientist Barry Allen sought to clear his father\'s name and find the real killer. After being doused in chemicals and struck by lightning, Barry was granted the gift of super-speed. Now he protects his hometown of Central City as The Flash, the fastest man alive and founding member of the Justice League.'),
(7, 'Black Widow', 'Natasha Romanova', 'F', 'Marvel Universe', 'Human', 'Expert tactician, hand-to-hand combatant and secret agent- Slowed aging, and enhanced immune system- Expert marksman and mastery of various other weapons.', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Black_Widow_1.jpg', 'A former KGB agent Natasha Romanova, better known as Black Widow, is one of the best agents S.H.I.E.L.D. has ever had. She\'s a longtime member of the Avengers as well as the leader of the short-lived Los Angeles-based superhero team called the Champions.'),
(8, 'Hawkeye', 'Clinton Francis \"Clint\" Barton', 'M', 'Marvel Universe', 'Human', 'Master archer and marksman, Expert tactician and hand-to-hand combatant, and Uses a variety of trick arrows.', 'https://upload.wikimedia.org/wikipedia/en/9/99/Hawkeye_%28Clinton_Barton%29.png', 'Trained by criminals and inspired by heroes, Clint Barton has grown from a troubled youth into one of the greatest heroes on Earth. The world knows him best as Hawkeye: Earth\'s Mightiest Marksman. A member of the Avengers for many years, he has left the team on occasion because of team friction. But he always returns, ready to face any threat.'),
(9, 'Thor', 'Thor Odinson', 'M', 'Marvel Universe', 'Alien', 'Superhuman strength, speed, durability and longevity, Abilities via Mjolnir, Dimensional transportation, Electric manipulation, Flight, and Weather manipulation.\n', 'https://upload.wikimedia.org/wikipedia/en/4/41/Thor-272.jpg', 'Thor is the Asgardian God of Thunder, and the son of the All-Father of Asgard Odin and the Elder Earth-Goddess Gaea. Combining the powers of Asgard and Midgard (Earth), Thor is arguably the greatest defender of both worlds. Armed with his enchanted Uru hammer Mjolnir, which can only be lifted by those who are worthy, Thor is the mightiest warrior in all of Asgard. A staunch ally for good and one of the strongest beings on Earth, Thor is also a founding member of the Avengers.'),
(10, 'Black Panther', 'T\'Challa', 'M', 'Marvel Universe', 'Human', 'The power to draw upon the knowledge, strength, and every experience of every previous Black Panther, Enhanced strength, speed, durability, and senses, Genius-level intellect, Master martial artist, Master tactician and strategist, Master inventor, and Utilizes vibranium suit and equipment.\n', 'https://upload.wikimedia.org/wikipedia/en/9/9f/Black_Panther_OS_Vol_1_2.png', 'T\'Challa is the Black Panther, king of Wakanda, one of the most technologically advanced nations on Earth. He is among the top intellects and martial artists of the world, a veteran Avenger, and a member of the Illuminati. Using his powers and abilities, he has pledged his fortune, powers, and life to the service of all mankind.'),
(11, 'Captain America', 'Steven \"Steve\" Rogers', 'M', 'Marvel Universe', 'Human', 'Peak human strength, speed, durability, agility, reflexes, senses, and mental processing, Master martial artist and hand-to-hand combatant\n Accelerated healing factor, Expert tactician, strategist, and field commander, and Wields vibranium-steel alloy shield.', 'https://upload.wikimedia.org/wikipedia/en/9/91/CaptainAmerica109.jpg', 'During World War II, Steve Rogers volunteered to receive the experimental Super-Soldier Serum. Enhanced to the pinnacle of human physical potential and armed with an unbreakable shield, he became Captain America. After a failed mission left him encased in ice for decades, he was found and revived by the Avengers. Later joining their ranks and eventually becoming the team\'s leader.'),
(12, 'Phantom Girl', 'Tinya Wazzo', 'F', 'DC Universe', 'Bgztl', 'Ability to phase-shift between Bgztl and Earth, making her able to phase through solid matter.', 'https://vignette.wikia.nocookie.net/marvel_dc/images/c/ce/Phantom_Girl_Pre-Zero_Hour_002.png/revision/latest?cb=20111008092124', 'Tinya Wazzo was the only Bgtzlian who could interact with the main universe. When she phased, she was visible in both universes, which could cause confusion. She\'s a member of the Legion of Super-Heroes as Phantom Girl. Of all of the Legionnaires, she digs the 21st century history the most and is considered the go-to expert on matters of legend.\nTinya is one of the few who know the truth behind Cosmic Boy\'s Dominator genocide plan, that they weren\'t exactly killed, as the public believe, but rather put in the Phantom Zone.'),
(13, 'Nightwing', 'Dick Grayson', 'M', 'DC Universe', 'Human', 'Agility, Escape Artist, Gadgets, Insanely Rich, Intellect, Leadership, Marksmanship, Power Suit, Stamina, Stealth, Tracking, Unarmed Combat, Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/10/100647/6436334-nightwing+39+yasmine+putri+variant.jpg', 'As the first Robin, Dick Grayson was the most famous sidekick in all of fiction. As he ventured forth on his own, he formed the Teen Titans and became their leader. When the boy became a man, he became the independent hero known as Nightwing.'),
(14, 'Iron Man', 'Tony Stark', 'M', 'Marvel Universe', 'Human', 'Blast Power, Electricity Control, Electronic interaction, Energy Absorption, Energy Shield, Flight, Force Field, Gadgets, Healing, Heat Generation, Holographic Projection, Implants, Insanely Rich, Intellect, Invulnerability, Leadership, Light Projection, Magnetism, Power Suit, Psionic, Radar Sense, Stamina, Stealth, Sub-Mariner, Super Speed, Super Strength, Technopathy, Tracking, Unarmed Combat, and Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/3/31666/4956367-invim2015001-maleevvar-d8a38.jpg', 'Tony Stark was the arrogant son of wealthy, weapon manufacturer Howard Stark. Tony cared only about himself, but he would have a change of heart after he was kidnapped by terrorists and gravely injured. Pressured to create a weapon of mass destruction, Stark instead created a suit of armor powerful enough for him to escape. Tony uses his vast resources and intellect to make the world a better place as the invincible Iron Man. Stark\'s super hero identity led him to become a founding member of the Avengers.'),
(15, 'Deadpool', 'Wade Wilson', 'M', 'Marvel Universe', 'Radiation', 'Adaptive, Agility, Controlled Bone Growth, Cosmic Awareness, Enhance Mutation, Escape Artist, Gadgets, Healing, Immortal, Invulnerability, Longevity, Marksmanship, Reality Manpulation, Stamina, Stealth, Super Speed, Super Strength, Swordsmanship, Teleport, Tracking, Unarmed Combat, and Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/3/31666/4943681-dpool2015007-cov-bec9c.jpg', 'Wade Wilson is a former test subject of the Weapon X program, where he received his regenerative healing factor through the scientific experiments conducted upon him. Deadpool\'s powers and personality traits combine to make a wild, mentally unstable, and unpredictable mercenary. Deadpool has been a member of X-Force and the Thunderbolts, and a self-professed member of the X-Men and the Avengers. The Merc with a Mouth is infamous for breaking the fourth wall.'),
(16, 'Green Arrow', 'Oliver Queen\n', 'M', 'DC Universe', 'Human', 'Adaptive, Agility, Escape Artist, Gadgets, Insanely Rich, Intellect, Leadership, Marksmanship, Stamina, Stealth, Super Sight, Swordsmanship, Tracking, Unarmed Combat, and Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/10/100647/6581972-4t0f7ihxo4g11.jpg', 'Oliver Queen was a spoiled, thrill-seeking playboy, until he was left stranded on a deserted island for several years. There, he trained to become a master archer in order to survive. After his return home, he used his new-found skills and his wealth to became the costumed vigilante known as Green Arrow.'),
(17, 'Wasp', 'Janet Van Dyne', 'F', 'Marvel Universe', 'Human', 'Agility, Animal Control, Blast Power, Escape Artist, Flight, Gadgets, Implants, Insanely Rich, Intellect, Leadership, Size Manipulation, Stealth, Super Speed, Super Strength,and Unarmed Combat.', 'https://static.comicvine.com/uploads/scale_small/10/100647/6039335-wasp.jpg', 'Genetically altered by Dr. Henry Pym, Janet Van Dyne gained the ability to alter her size, fly at rapid speeds and fire bio-electric energy stings. Calling herself the Wasp, she became Pym\'s superhero partner. Later, she became a founding member and the first female member of the Avengers.'),
(18, 'Supergirl', 'Kara Kent', 'F', 'DC Universe', 'Alien', 'Agility, Berserker Strength, Energy Absorption, Flight, Healing, Heat Vision, Ice Breath, Intellect, Invisibility, Invulnerability, Leadership, Levitation, Longevity, Marksmanship, Omni-lingual, Sonic Scream, Stamina, Super Hearing, Super Sight, Super Smell, Super Speed, Super Strength, Tracking, Unarmed Combat, Vibration Wave, and Wind Bursts.', 'https://static.comicvine.com/uploads/scale_small/11115/111156051/6610574-supergirl-cover-22.jpg', 'Kara Zor-El is Superman\'s cousin and last survivor of Krypton\'s Argo City. She has a brash and defiant personality that she developed in response to the destruction of Krypton. Currently, she is operating out of National City alongside the D.E.O.'),
(19, 'Aquaman', 'Arthur Curry', 'M', 'DC Universe', 'Other', 'Agility, Animal Control, Electricity Control, Healing, Ice Control, Insanely Rich, Intellect, Invulnerability, Leadership, Longevity, Power Item, Radar Sense, Stamina, Sub-Mariner, Super Hearing, Super Sight, Super Speed, Super Strength, Swordsmanship, Telepathy, Teleport, Unarmed Combat, Water Control, and Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/10/100647/6198659-dprxkvjwaaa9eni.jpg', 'The son of an Atlantean queen and a lighthouse keeper from the town of Amnesty Bay, Arthur Curry would grow up to become the superhero Aquaman, and later take on his birthright as the King of Atlantis. He is a founding member of the Justice League and is among DC Comics\' most recognized heroes.'),
(20, 'Starfire', 'Kory Anders', 'F', 'DC Universe', 'Alien', 'Agility, Astral Projection, Berserker Strength, Blast Power, Energy Absorption, Energy Manipulation, Energy-Enhanced Strike, Flight, Intellect, Invulnerability, Levitation, Omni-lingual, Stamina, Super Sight, Super Strength, Unarmed Combat, and Willpower-Based Constructs.', 'https://static.comicvine.com/uploads/scale_small/10/100647/5432011-starfire_lr12.jpg', 'Formerly warrior Princess Koriand\'r of the now-destroyed planet Tamaran, Starfire found a new home on Earth and a new family in the Teen Titans. She was once romantically involved with Dick Grayson, and often dealt with hostilities from her older sister Blackfire. Starfire has also served with many other teams such as the Outsiders, Justice League, R.E.B.E.L.S. and Jason Todd\'s Outlaws.');


ALTER TABLE `Superheroes`
  ADD PRIMARY KEY (`hero_id`),
  ADD KEY `hero_id` (`hero_id`);

ALTER TABLE `Superheroes`
  MODIFY `hero_id` tinyint(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;


-- 
-- CREATE VILLAINS TABLE
-- 

CREATE TABLE IF NOT EXISTS `Villains` (
  `villain_id` int(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `fullName` varchar(50) NOT NULL,
  `gender` varchar(5) NOT NULL,
  `universe` varchar(1000) NOT NULL,
  `race` varchar(1000) NOT NULL,
  `powers` varchar(1000) NOT NULL,
  `img` varchar(1000) NOT NULL,
  `bio` varchar(5000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- 
-- INSERT VILLAINS DATA
-- 

INSERT INTO `Villains` (`villain_id`, `name`, `fullName`, `gender`, `universe`, `race`, `powers`, `img`, `bio`) VALUES
(1, 'Joker', 'Eric Border', 'M', 'DC Universe', 'Human', 'Adaptive, Agility, Enhance Mutation, Escape Artist, Gadgets, Healing, Insanely Rich, Intellect, Leadership, Marksmanship, Poisonous, Stamina, Stealth, Unarmed Combat, and Weapon Master.', 'https://www.dccomics.com/sites/default/files/styles/character_thumb_160x160/public/CharThumb_215x215_joker_52ab8f442079b0.32576403.jpg?itok=vsb67tNU', 'The Joker, Clown Prince of Crime, is Batman\'s arch-nemesis. An agent of chaos known for his malicious plots, wacky gadgets and insidious smile, he has caused Batman more suffering than any other villain he has ever faced. His origin, name, and true motivations remain a mystery.'),
(2, 'Lex Luthor', 'Alexander Luthor', 'M', 'DC Universe', 'Human', 'Blast Power, Energy Manipulation, Energy Shield, Flight, Force Field,Gadgets, Insanely Rich,Intellect, Leadership, Power Item, Power Suit, Probability Manipulation, Radiation, Stamina, Super Strength, Time Travel, Unarmed Combat, and Weapon Master.', 'https://vignette.wikia.nocookie.net/marvel_dc/images/c/cd/Lex_Luthor_American_Alien_02.jpg/revision/latest?cb=20160428025051', 'Lex Luthor, Superman\'s arch-nemesis, is one of the most brilliant men alive, whose hatred of interfering aliens pushes him down the path of a sociopath. Known for his ends justifies the means approach to life, his single-minded and often brutal focus puts him at odds with The Man of Steel. Luthor is arguably DC Comics\' most iconic villain.'),
(3, 'Poison Ivy', 'Pamala Isley', 'F', 'DC Universe', 'Other', 'Adaptive, Agility, Chemical Absorbtion, Chemical Secretion, Death Touch, Emotion Control, Genetic Manipulation, Healing, Hypnosis, Intellect, Marksmanship, Mesmerize, Pheromone Control, Plant Control, Poisonous, Prehensile Hair, Stamina, Swordsmanship, Tracking, Unarmed Combat, and Weapon Master.\n', 'https://i.pinimg.com/originals/c6/ff/50/c6ff50c7c03a7b571220521d059f5af7.jpg', 'A brilliant botanical biochemist, Pamela Isley is a fervent eco-terrorist out to save the world\'s plant life by any means necessary. She often finds herself at odds with Batman, though they have, on occasion, fought on the same side.'),
(4, 'Sinestro', 'Thaal Sinestro', 'M', 'DC Universe', 'Alien', 'Blast Power, Energy Absorption, Energy Based Constructs, Energy-Enhanced Strike, Flight, Force Field, Healing, Holographic Projection,Intellect,Leadership, Light Projection, Phasing / Ghost, Power Item, Stamina, Super Speed, Super Strength, Unarmed Combat, and Willpower-Based Constructs.', 'https://vignette.wikia.nocookie.net/marvelcrossroads/images/e/ee/Sinestro_%288026%29.jpg/revision/latest?cb=20160327010602', 'Once considered the greatest Green Lantern in any sector, Sinestro came to believe that the only way to ensure order in the universe was through the reign of fear, a crime for which the Guardians banished him to Qward. There he created the first yellow power ring and later on founded his own corps, The Sinestro corps. He has clashed frequently with his former student and protege, Hal Jordan the relationship between the two is a complicated one, a mixture of both hatred and respect in equal measures.'),
(5, 'Brainiac', 'Milton Fine', 'M', 'DC Universe', 'God/Eternal', 'Adaptive, Berserker Strength, Blast Power, Divine Powers, Electricity Control, Electronic Disruption, Electronic interaction, Energy Manipulation, Energy Shield, Escape Artist, Flight, Force Field, Gadgets, Healing, Implants, Intellect, Invulnerability, Longevity, Omni-lingual, Power Suit, Psionic, Psychic, Shape Shifter, Siphon Abilities, Stamina, Super Speed, Super Strength, Technopathy, Telekinesis, Telepathy, Teleport, Time Travel, and Weapon Master.', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Brainiac_%28DC_Comics%29.png/201px-Brainiac_%28DC_Comics%29.png', 'Brainiac is one of Superman\'s oldest and most powerful foes. A techno-organic being with a twelfth-level intellect and hyper-advanced technology, he travels the multiverse seeking civilizations to shrink and abduct, which he then adds to his collection of captured worlds. He has been responsible for the extinction of countless cultures and the deaths of untold billions.'),
(6, 'Venom', 'Eddie Brock', 'M', 'Marvel Universe', 'Human', 'Agility, Berserker Strength, Claws, Elasticity, Enhance Mutation, Feral, Healing, Marksmanship, Power Suit, Stamina, Super Speed, Super Strength, Unarmed Combat, Wall Clinger, Weapon Master, and Webslinger.', 'https://images.complex.com/complex/images/c_limit,w_680/fl_lossy,pg_1,q_auto/gxdr5aesylxo7pixbdfx/venom-you-die', 'Eddie Brock bonded to the alien symbiote after it was discarded by Spider-Man, becoming the first Venom. Brock was later Anti-Venom, but the symbiote was lost during Spider-Island. Brock has also been forcibly bonded to the Toxin symbiote by the Crime Master, but has reluctantly given it up to stop Carnage. He has recently been rebonded with Venom.'),
(7, 'Mystique', 'Raven Darkholme', 'F', 'Marvel Universe', 'Mutant', 'Adaptive, Agility, Chameleon, Claws, Elasticity, Escape Artist, Healing, Insanely Rich, Intellect, Leadership, Longevity, Marksmanship, Shape Shifter, Stamina, Stealth, Tracking, Unarmed Combat, and Weapon Master.', 'https://cmro.travis-starnes.com/images/characters/mystique.jpg', 'True to her name, the shape shifting Mystique is an enigma. Is she a mutant terrorist determined to bring about the end of humanity, or a misguided mutant with a good heart?'),
(8, 'Enchantress', 'Christine Collins', 'F', 'Marvel Universe', 'God/Eternal', 'Agility, Animation, Astral Projection, Blast Power, Chameleon, Chemical Secretion, Dimensional Manipulation, Divine Powers, Energy Manipulation, Energy Shield, Escape Artist, Fire Control, Flight, Force Field, Healing, Hypnosis, Illusion Casting, Immortal, Intellect, Invulnerability, Leadership, Levitation, Longevity, Magic, Mesmerize, Necromancy, Pheromone Control, Psionic, Shape Shifter, Stamina, Super Hearing, Super Sight, Super Strength, Telepathy, Teleport, and Unarmed Combat.\n', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Enchantress_DC_Comics.png/250px-Enchantress_DC_Comics.png', 'Amora the Enchantress, An Asgardian Goddess and immensely powerful magical sorcerer. Being backed by years of experience, she is one of Thor’s greatest and most powerful foes not only because of her immense power, but also because of him being her love interest.'),
(9, 'Selene ', 'Selene Gallio', 'F', 'Marvel Universe', 'Mutant', 'Adaptive, Animal Control, Animation, Astral Projection, Blast Power, Chameleon, Claws, Controlled Bone Growth, Cosmic Awareness, Darkforce Manipulation, Darkness Manipulation, Death Touch, Density Control, Dimensional Manipulation, Divine Powers, Earth Manipulation, Elasticity, Emotion Control, Empathy, Energy Absorption, Energy Based Constructs, Energy Shield, Energy-Enhanced Strike, Escape Artist, Fire Control, Flight, Force Field, Healing, Heat Generation, Hypnosis, Ice Control, Illusion Casting, Immortal, Insanely Rich, Intellect, Invisibility, Invulnerability, Leadership, Levitation, Longevity, Magic, Mesmerize, Necromancy, Psionic, Sense Death, Shadowmeld, Siphon Lifeforce, Soul Absorption, Super Strength, Telekinesis, Telepathy, Teleport, and Vampirism.', 'https://vignette.wikia.nocookie.net/marveldatabase/images/3/35/Selene_Gallio_%28Earth-616%29_from_X-Men_Vol_4_11_%28Cover%29.png/revision/latest?cb=20140221064328', 'Selene is the oldest living mutant, born 17,000 years ago. She is a notable villain of the X-Men, often opposing them in her position as the Black Queen of the Hellfire Club. Her ultimate goal is to become a goddess through the life absorption of other mutants.'),
(10, 'Leader', 'Samuel Sterns', 'M', 'Marvel Universe', 'Radiation', 'Blast Power, Flight, Gadgets, Intellect, Leadership, Possession, Power Suit, Precognition, Psionic, Psychic, Radiation, Telekinesis, Telepathy, and Unarmed Combat.\n', 'https://vignette.wikia.nocookie.net/marveldatabase/images/e/e5/Samuel_Sterns_%28Earth-616%29_from_Incredible_Hulk_Vol_1_603.jpg/revision/latest?cb=20151225193000', 'Samuel Sterns was a worker in a chemical plant in a menial capacity until an accident working with radioactive material bombarded him with gamma radiation, turning his skin green and making his head grow, filling it with extreme knowledge. He became the one who men call The Leader and was one of Hulk\'s arch-enemies.'),
(11, 'Magneto\n', 'Max Eisenhardt', 'M', 'Marvel Universe', 'Mutant', 'Blast Power, Electricity Control, Electronic Disruption, Energy Manipulation, Energy Shield, Flight, Force Field, Gadgets, Gravity control, Intellect, Invulnerability, Leadership, Levitation, Longevity, Magnetism, Stamina,Super Strength, and Unarmed Combat.', 'https://static.comicvine.com/uploads/scale_small/10/100647/6197696-inhumans+vs.+x-men+3.jpg', 'Among the most powerful, recognizable, and infamous mutants to inhabit the planet Earth, Magneto was the X-Men\'s first major nemesis. Now known as a revolutionist and terrorist, Magneto has fought for the X-Men as many times as he’s been against them.'),
(12, 'Doctor Doom', 'Victor Von Doom', 'M', 'Marvel Universe', 'Human', 'Adaptive, Agility, Blast Power, Divine Powers, Electricity Control, Electronic Disruption, Energy Absorption, Energy Based Constructs, Energy Manipulation, Energy Shield, Energy-Enhanced Strike, Escape Artist, Flight, Force Field, Gadgets, Genetic Manipulation, Healing, Holographic Projection, Hypnosis, Illusion Casting, Immortal, Insanely Rich, Intellect, Invulnerability, Leadership, Levitation, Magic, Mesmerize, ecromancy, Omni-lingual, Possession, Power Item, Power Suit, Psionic, Psychic, Radar Sense, Siphon Abilities, Size Manipulation, Stamina, Stealth, Sub-Mariner, Super Hearing, Super Sight, Super Smell, Super peed, Super Strength, Swordsmanship, Technopathy, Telekinesis, Teleport, Time Manipulation, Time Travel, Tracking, Unarmed Combat, Voice-induced Manipulation, Weapon Master, and Willpower-Based Constructs.\n', 'https://static.comicvine.com/uploads/scale_small/3/31666/5396961-infim2016002-albuquerquevar-23648.jpg', 'The very mention of his name makes lesser men tremble! The brilliant scientist with the iron mask which conceals his now scarred but once handsome face! Master of science and sorcery, Victor Von Doom is the monarch of Latveria and seeks the betterment of mankind through world conquest! Unequaled and unrivaled in every manner, Doctor Doom has had many conflicts with both earthly and cosmic super-beings but he will always be known as the eternal nemesis of Reed Richards and his accursed Fantastic Four!'),
(13, 'Ra\'s al Ghul', 'Ra\'s al Ghul', 'M', 'DC Universe', 'Human', 'Agility, Astral Projection, Escape Artist, Gadgets, Healing, Immortal, Insanely Rich, Intellect, Leadership, Longevity, Magic, Marksmanship, Necromancy, Possession, Stamina, Stealth, Swordsmanship, Unarmed Combat, Weapon Master', 'https://vignette.wikia.nocookie.net/batman/images/9/9b/Ra%27s_al_Ghul-1.jpg/revision/latest?cb=20100916212838', 'Ra\'s al Ghul, whose name translates to The Demon\'s Head in Arabic, is the centuries-old leader of the League of Assassins. He sees humanity as a cancer poisoning the Earth, and seeks to eliminate most of them in order to stave off environmental disaster. He has clashed frequently with Batman, whom he hoped to make his successor.'),
(14, 'Loki', 'Loki Laufeyson', 'M', 'Marvel Universe', 'God/Eternal', 'Agility, Animation, Astral Projection, Chameleon, Cosmic Awareness, Darkness Manipulation, Dimensional Manipulation, Divine Powers, Duplication, Earth Manipulation, Empathy, Energy Absorption, Energy Manipulation, Energy Shield, Flight, Force Field, Healing, Hypnosis, Illusion Casting, Immortal, Intellect, Invisibility, Invulnerability, Levitation, Longevity, Magic, Mesmerize, Power Item, Power Mimicry, Psionic, Radiation, Shape Shifter, Size Manipulation, Stamina, Stealth, Super Hearing, Super Sight, Super Speed, Super Strength, Swordsmanship, Telepathy, Teleport, Time Travel, Unarmed Combat, Wall Clinger, and Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/11112/111126675/5889253-loki+2.jpg', 'Loki is the Jötunn/Asgardian God of Mischief and Prince of Lies, the adopted son of Odin and typically the archenemy of his brother, Thor, as well as the adoptive brother to former Guardian of the Galaxy, Angela. Loki has schemed against Thor and Asgard for ages and his cosmic meddling led to the formation of the Avengers. Recently reincarnated as a teen, he has decided to try to reform, and is now a part of the Young Avengers.'),
(15, 'Viper', 'Ophelia Sarkissian', 'F', 'Marvel Universe', 'Human', 'Agility, Chemical Secretion, Escape Artist, Insanely Rich, Intellect, Leadership, Longevity, Marksmanship, Mesmerize, Poisonous, Stamina, Stealth, Swordsmanship, Teleport, Tracking, Unarmed Combat, and Weapon Master.\n', 'https://static.comicvine.com/uploads/scale_small/2/25835/1039666-tumblr_krttk6azud1qzs9o3.jpg', 'Viper is the former terrorist leader of HYDRA and an enemy of Captain America, Nick Fury and Wolverine among many others.'),
(16, 'Madame Masque', 'Giuletta Kristina Nefaria', 'F', 'Marvel Universe', 'Human', 'Gadgets, Insanely Rich, Intellect, Leadership, Marksmanship, Shape Shifter, Unarmed Combat, and Weapon Master.\n', 'https://static.comicvine.com/uploads/scale_small/11114/111147698/4876303-4874467-ironman.jpg', 'Raised as a wealthy socialite, Whitney Frost was initially horrified to learn of her true heritage as the daughter of the Maggia-leader Count Nefaria. Hiding her face behind a golden mask after horrible scarring, she has been driven mostly by vengeance against her father which has placed her on both sides of the law.'),
(17, 'Sin', 'Sinthia Schmidt', 'F', 'Marvel Universe', 'Mutant', 'Leadership, Marksmanship, Unarmed Combat, and Weapon Master.', 'https://static.comicvine.com/uploads/original/0/77/150825-104753-sin.jpg', 'The daughter of the Red Skull who was aged at an accelerated rate by means of advanced technology so she could be of use to her father.'),
(18, 'Harley Quinn', 'Harleen Frances Quinzel', 'F', 'DC Universe', 'Human', 'Agility, Gadgets, Healing, Intellect, Marksmanship, Stamina, Stealth, Super Strength, Unarmed Combat, and Weapon Master.', 'https://static.comicvine.com/uploads/scale_small/11118/111185556/5296059-harley+quinn+by+stanley+lau.jpg', 'Harleen Quinzel was a psychiatric resident at Arkham Asylum, where she met the incarcerated Joker. Falling in love with her patient, she conspired to break him out of prison and eventually became his lover and loyal sidekick, Harley Quinn.'),
(19, 'Cheetah (Minerva)', 'Barbara Ann Minerva', 'F', 'DC Universe', 'Human', 'Agility, Animal Control, Claws, Divine Powers, Feral, Intellect, Sense Death, Shape Shifter, Stealth, Super Hearing, Super Sight, Super Smell, Super Speed, Super Strength, and Unarmed Combat.', 'https://www.picturesboss.com/?d=4QVFtIr27iELtBvEoNk58KblHgbJCYYpb_L7MxgSvnCaplYMMOnMYuN1iU0uXd6asYfTUJMnokFsyu0eweCuHuuS1DCdiNJKSpa0nfynf1ZCEBF43SnOOM6LmV62FXqCmLV6QFQSKhIdXt8QL1r050BBvjHno5x1yA8EtKeP0-Q', 'Barbara Ann Minerva was an archaeologist who used an ancient ritual to turn herself into the avatar of Urzkartaga, but because she didn\'t meet the requirement of virginity, she was cursed by the god to suffer from an unending hunger for human flesh.');


ALTER TABLE `Villains`
  ADD PRIMARY KEY (`villain_id`),
  ADD KEY `villain_id` (`villain_id`);

ALTER TABLE `Villains`
  MODIFY `villain_id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;
COMMIT;

-- 
-- Users Table
-- 

CREATE TABLE IF NOT EXISTS `Users` (
  `user_id` int(10) NOT NULL,
  `username` varchar(30) NOT NULL,
  `password` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `Users` (`user_id`, `username`, `password`) VALUES
(1, 'admin', 'testing');

ALTER TABLE `Users`
  ADD PRIMARY KEY (`user_id`);

ALTER TABLE `Users`
  MODIFY `user_id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;